# Generated by Django 2.2 on 2020-11-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnj', '0002_auto_20201104_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='No Value', max_length=255),
            preserve_default=False,
        ),
    ]
