# Generated by Django 2.2 on 2020-11-04 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djnj', '0003_dojo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='desc',
        ),
    ]
