# Generated by Django 2.2 on 2020-11-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnj', '0004_remove_dojo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='old dojo', max_length=255),
            preserve_default=False,
        ),
    ]
